networks:
  traefik-public:
    driver: bridge

services:
  traefik:
    image: traefik:v3.1
    command:
      - "--providers.file=/etc/traefik/traefik.yml"
      - "--api.insecure=true"

    ports:
      - "80:80"
      - "8080:8080"  # Traefik Dashboard
      - "8081:8081"  # Metrics endpoint
      - "443:443"  # HTTPS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml  # Mount the configuration file
      - ./acme.json:/acme.json  # Mount the Let's Encrypt certificate storage
      - ./access.log:/var/log/traefik/access.log  # Mount the access log
    networks:
      - traefik-public
      - default

    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/ping"]
      interval: 5s
      timeout: 5s
      retries: 6



  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - traefik-public
    ports:
      - "9090:9090"
    depends_on:
      traefik:
        condition: service_healthy


  grafana:
    image: grafana/grafana
    networks:
      - traefik-public
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Set a password for the admin user
    depends_on:
      - prometheus
    volumes:
      - ./grafana-data:/var/lib/grafana
  
  serviceError:
    image: nginx
    volumes:
      - ./error.html:/usr/share/nginx/html/429.html
    networks:
      - traefik-public
    

  service-image:
    image: nginx:alpine
    networks:
      - traefik-public

  service-image-2:
    image: nginx:alpine
    networks:
      - traefik-public
  