global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'traefik'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['traefik:8081'] # Adjust based on your Traefik service configuration

